### ISSUE TITLE
gcc-10 compile fail

### ISSUE THREAD

**Issue by acoul** [gamelinux/passivedns#115]
Greetings,

gcc-10 fails to compile passivedns

the attached patch resolves this issue

[gcc-10_patch.txt](https://github.com/gamelinux/passivedns/files/5089290/gcc-10_patch.txt)

**Comment by Hexhu** [comment]
Thanks for this awesome patch!

**Comment by m040601** [comment]
Yeap. Something happened to me in ArchLinux.
@acoul: Thanks for the patch.

I also checked the github pull requests queue. Couldnt find anything related ??? 

Many old pull requests unanswered, for more than a year ago.
Cant see any trace of "gamelinux" the project owner.

Is this project still actively maintained ?
Any chance that it will be merged ?

**Comment by gamelinux** [comment]
Patched in 8b485bbb8f316c129ee673abaf34fe221149acc7. And its alive!
