### ISSUE TITLE
Is this project still maintained ?

### ISSUE THREAD

**Issue by m040601** [gamelinux/passivedns#116]
Such a usefull little tool.
Thanks for all the work done with it.

I had an issue, https://github.com/gamelinux/passivedns/issues/115 fortunately solved by another user.

I checked the github pull requests queue.
Many old pull requests unanswered, for more than a year ago.
Same thing with the issues queue.
Cant see any trace of "gamelinux" the project owner.
His last commit here, in this project, is from 2018.
His last activity in github is from December 2019

Is this project still actively maintained ?

**Comment by gamelinux** [comment]
Hi all!

I just wanted to say, that my 2FA Authentication codes (on both my phones) stopped working some time e few months back!

My recovery codes did not work eater! Today, I found a VM that had my recovery codes from PRE Januar 2019!!! And I tried those! It worked!

So I hope I will be able to update my projects from now on!

Sorry for my absence! Hope this S*#"¤7 does not happen again!

E
