### ISSUE TITLE
explicit license

### ISSUE THREAD

**Issue by zabbal** [gamelinux/passivedns#42]
I've looked up license in file headers in src but would be nice to add explicit COPYING or LICENSE file the same way it's done in many other repo.

While we're at it - any specific reason not to use GPLv3+ instead of v2?

**Comment by thus** [comment]
The license file is located in "doc/LICENSE", so I think we're in the clear even though it's not located in the root or source directories.

I'm no expert in copyright nor am I the original author of passivedns. However, I wouldn't change the license of the software without the agreement of the people who has contributed to it. And that seems like a tedious and time consuming task that uses a lot of time better spent on writing more code :)

**Comment by thus** [comment]
No more replies, so closing this issue.
