### ISSUE TITLE
Distribution: Add to FreeBSD ports

### ISSUE THREAD

**Issue by shadowbq** [gamelinux/passivedns#47]
I've created a "shar" with the applicable service 'rc.d' wrappers, and make files to install passivedns on FreeBSD. 

It uses a "hash ref" as there has not been a release in over 2 years.

I've submitted the request and it can be tracked here:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198499

**Comment by shadowbq** [comment]
FYI: Track from github commit a6c7e26

**Comment by shadowbq** [comment]
This is the ports submission (not a fork of the passivedns source) https://github.com/shadowbq/freebsd-port-passivedns

**Comment by thus** [comment]
Closing issue, since it's not really a issue. Thanks for the ports submission :)
