### ISSUE TITLE
Provide complete build-ready release

### ISSUE THREAD

**Issue by dspruell** [gamelinux/passivedns#48]
Would it be possible to provide build-ready releases of passivedns? By this I mean distributed ready for build, with the configure script present and the build being possible as common with typical Unix software:

    ./configure
    make
    make install

It would be nice to see an end to dependencies like autoconf and automake for building passivedns, which is itself a very lightweight piece of software and should be quick to deploy anywhere. Portability on some platforms like OpenBSD or on some embedded systems where running the collector makes sense (routers/firewalls) is made more complicated by additional dependencies. Also for producing ports/packages for new platforms and/or deploying via SCM (Puppet, Salt, Ansible, etc.) a simplified build process will help greatly.

Thinking it would simplify the INSTALL document also as the process would be simplified and consistent on every platform once ldns is installed. (And if the build is simplified, this will encourage creation of packages for more systems and the package will simply be available in your choice of distribution's repositories).

**Comment by thus** [comment]
I like to keep the development tree as clean of "build" files as possible, so I don't think this is such a great idea. I tend to have one build machine that need autoconf and automake, none of the other machines running passivedns have these dependencies.

What's your take on this @gamelinux?

**Comment by gamelinux** [comment]
The initial idea was that passivedns would be small and easy to install. But as a project grows, more use cases needs to be addressed. Autoconf/make are helpfull, and here to stay, and people also pack theire own .deb/.rpm/"puppet" packages and ship them out as far as Im aware of. I think a sysadmin would work this pretty well as it is.
