### ISSUE TITLE
Track timestamp in log files as YYYY-MM-DD HH:MM:SS

### ISSUE THREAD

**Issue by dsdee** [gamelinux/passivedns#58]
Made modifications to track the timestamp in the logfiles as YYYY-MM-DD HH:MM:SS
'field' parameter 'H' adds this capability.

(figured out how to do a pull request, i will this to you in a bit)

**Comment by thus** [comment]
Closing this issue, since the pull request was accepted.

**Comment by kkplein** [comment]
Not sure if replying in this closed thread is the right way.... but... how do we enable this behaviour? Now we're getting timestamps like this:
1479213824.636482||10.19.231.6||192.x.y.z||IN||a1402.dspw40.akamai.net.||A||77.67.4.50||13||1
and we would like YYYY-MM-DD HH:MM:SS

**Comment by d2inco** [comment]
passivedns -h shows you help text.  Use a "H" in your "-f" (fields) parameter fot YMD-HMS format timestamp.

**Comment by kkplein** [comment]
Hi d2imco,

Thanks, the -h switch turned out to be very useful! :-)
