### ISSUE TITLE
97% Total DNS packets over UDP failed

### ISSUE THREAD

**Issue by udalite** [gamelinux/passivedns#61]
Hey there,

I've got a problem while using passivedns. About 97% DNS packets are marked as "failed" in statistics.

I compiled pdns with DEBUG and found that it comes from ldns: [dns.c:94(dns_parser)] [D] ldns_wire2pkt status: 48. 

What's wrong with my traffic and is it possible to solve?

Appreciate any help

Thanks!

**Comment by udalite** [comment]
Solved - problem literally was in traffic

**Comment by stamper197** [comment]
Hello how were you able to fix this? I am having the same issue, you stated it was a problem with your traffic?
