### ISSUE TITLE
Potential deadlock?

### ISSUE THREAD

**Issue by Maxtors** [gamelinux/passivedns#65]
Not quite sure what this issue is, so i'm gonna describe it with what i have now, and if you have anything more i should check i can  gladly do that.

After running for a while, i see that alot of my passivends installations stop. Well, the application has not quit, but it gives no ouput to the passivedns.log file. There was disk space, DNS traffic on the wire, but no output to the log.

Version:
[*] PassiveDNS 1.2.0
[*] By Edward Bjarte Fjellskål <edward.fjellskaal@gmail.com>
[*] Using libpcap version 1.5.3
[*] Using ldns version 1.6.17

OS: CentOS release 6.7 (Final), 3.10.90-1.

Running strace just gave this output, and it did nothing after that, just standing there.

strace -p `pidof passivedns`
Process 10859 attached
futex(0x30a5b8fe80, FUTEX_WAIT, 2, NULL

**Comment by thus** [comment]
A few questions:
- what parameters do you pass passivedns on startup?
- did this happen to all instances of passivedns at the same time?
- do you have any cron-jobs running at the time it stopped working, or perhaps logrotate?

**Comment by thus** [comment]
If you got gcore (usually installed with gdb) installed, you could do a core dump of the running passivedns process while it hangs. That would make the debug process a whole lot easier.

**Comment by Maxtors** [comment]
- No special parameters appart from interface, daemonize, pidfile, logfile.
- Was discovered by chance, but at that point alot (most) instances had to be restarted, so seeing that we automate distribution of code and recently upgraded to the latest version (havent seen this before) and this distribution happens at the same time it might be a common issue based on how long they ran.
- We rotate the files every hour. mf -v <logfile> <to_dir> >/dev/null 2>&1 and a kill -HUP `cat $PIDFILE`.

Will try and get a gcore dump next time i see this.

**Comment by thus** [comment]
I've had a similar problem some times with high traffic passivedns instances. I think I know what's causing it. I'll have a look at it when I'll get the chance.

**Comment by thus** [comment]
This issue is hopefully fixed in c5b6cc7. Please try the newest git version and let me know if you are still experiencing this issue.

**Comment by thus** [comment]
No more comments from reporter, so closing issue.
