### ISSUE TITLE
Build issue on OSX El Capitan

### ISSUE THREAD

**Issue by jack8daniels2** [gamelinux/passivedns#74]
The first hurdle is lack of openssl libraries. It can be overcome by pointing to OSX native openssl libraries

    ./configure --with-openssl-includes=/usr/local/opt/openssl/include --with-openssl-libraries=/usr/local/opt/openssl/lib

But then make fails with the following error -

    make 
    Making all in src
    /Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
    make[1]: Nothing to be done for `all-am'.

**Comment by thus** [comment]
Could you try doing a "make clean" before "make"?

Sometimes it won't work if you have already tried running make.

**Comment by jack8daniels2** [comment]
That worked. Thanks
