### ISSUE TITLE
What is 'count' column in log file

### ISSUE THREAD

**Issue by RamadhanAmizudin** [gamelinux/passivedns#83]
Hi, as per title. What is count column in log file?

Thanks

**Comment by thuvh** [comment]
[This paper ](http://www.ru.nl/publish/pages/769526/z-thesis_pedroluz.pdf) uses this tool to collect data, and the author said about the column. You can refer to it.

**Comment by gamelinux** [comment]
How many times the "Query" has been queried within the cached period.

**Comment by alenazi90** [comment]
@gamelinux How can a "query" be queried again while cache is available
