### ISSUE TITLE
We need an INSTALL file in the distribution

### ISSUE THREAD

**Issue by marcopaganini** [gamelinux/passivedns#85]
Hello there,

I've noticed that there's no INSTALL file in the distribution or a familiar "configure" script to generate the make file. Similarly, there's no information about dependencies.

I've installed by running autoconf directly:

libtoolize --force
aclocal
autoheader
automake --force-missing --add-missing
autoconf
./configure

But I confess I hadn't used those tools in a while and a Google query was required to get the right commands.

Maybe this should be added to the INSTALL file, or (even better) a configure file shipped with the repo?

**Comment by frsk** [comment]
There's already an INSTALL file present in the doc directory. It contains the steps to compile passivedns on some of the most common distributions out there, as well as requirements.

**Comment by marcopaganini** [comment]
Fantastic, thanks! Usually INSTALL and README are at the top level (I usually assume doc directories contain manpages and others that will be installed). Closing the bug.
