### ISSUE TITLE
Can not see field name of log file

### ISSUE THREAD

**Issue by whitetiger21022014** [gamelinux/passivedns#91]
Hello,
I just compiled pdns from github on Ubuntu 16
passivedns -i ens33 -l /var/log/passivedns.log
cat /var/log/passivedns.log | more

1491137669.908593||192.168.111.144||192.168.111.2||IN||google.com.||A||172.217.24.46||5||1
1491137670.118196||192.168.111.144||192.168.111.2||IN||46.24.217.172.in-addr.arpa.||PTR||hkg07s23-in-f14.1e100.net.||5||1
1491137670.118196||192.168.111.144||192.168.111.2||IN||46.24.217.172.in-addr.arpa.||PTR||hkg07s23-in-f46.1e100.net.||5||1

but can NOT see header name as  #timestamp||dns-client||dns-server||RR class||Query||Query Type||Answer||TTL

Thanks,

**Comment by gamelinux** [comment]
They are not there... if one where to add it, it should be an enhancement, and optional
