### ISSUE TITLE
Logging queries to non-existent domains

### ISSUE THREAD

**Issue by Hitroscop** [gamelinux/passivedns#93]
Hi!
It seems like passivedns does not collect queries to unexistent domains - when I make nslookup to such domains there is no log record for this query. Is it unrealized feature or some configuration should be done to capture such queries?

**Comment by thus** [comment]
Hi, @Hitroscop.

You must specify the server return code errors (and records types) you want to log (e.g. NXDOMAIN) using '-X' when starting passivedns. The output when running `passivedns -h` gives you all the possible record types and error types (on the bottom).

**Comment by Hitroscop** [comment]
Thank you, @thus!
