### ISSUE TITLE
./passivedns: No such file or directory

### ISSUE THREAD

**Issue by gnomefish** [gamelinux/passivedns#96]
Hi there, I followed the instructions but for some reason I can't run passivedns (tried Ubuntu 1404 and 16.04) "./passivedns: No such file or directory"

root@UB14METASPLOIT:/opt/passivedns# make
Making all in src
make[1]: Entering directory `/opt/passivedns/src'
gcc -O3  -c passivedns.c -o passivedns.o
gcc -O3  -c dns.c -o dns.o
gcc -o passivedns passivedns.o dns.o -lpcap -lldns
make  all-am
make[2]: Entering directory `/opt/passivedns/src'
make[2]: Leaving directory `/opt/passivedns/src'
make[1]: Leaving directory `/opt/passivedns/src'
make[1]: Entering directory `/opt/passivedns'
make[1]: Nothing to be done for `all-am'.
make[1]: Leaving directory `/opt/passivedns'
root@UB14METASPLOIT:/opt/passivedns# ll
total 576
drwxr-xr-x 9 root root   4096 Jul  9 11:54 ./
drwxr-xr-x 5 root root   4096 Jul  9 11:53 ../
-rw-r--r-- 1 root root  41927 Jul  9 11:53 aclocal.m4
*** SNIP ****
drwxr-xr-x 2 root root   4096 Jul  9 11:53 www/
root@UB14METASPLOIT:/opt/passivedns# ./passivedns
-bash: ./passivedns: No such file or directory

**Comment by gnomefish** [comment]
my bad... nevermind

**Comment by brosev** [comment]
@gnomefish Im having a similar issue, where did you find?
